server:
  port: 8080
  servlet:
    context-path: /${dummyjson.api-environment}

spring:
  application:
    name: dummyjson-client
  profiles:
    active: production
  jmx:
    enabled: false

management:
  endpoints:
    web:
      base-path: /health
      exposure:
        include:
          - health
          - info
          - metrics

---

spring:
  config:
    activate:
      on-profile: production
dummyjson:
  product-url: https://dummyjson.com/products
  api-environment: api
---

spring:
  config:
    activate:
      on-profile: development

dummyjson:
  product-url: https://dummyjson.com/products
  api-environment: api-dev

---

spring:
  config:
    activate:
      on-profile: homologation

dummyjson:
  product-url: https://dummyjson.com/products
  api-environment: api-hmg

---

spring:
  config:
    activate:
      on-profile: test

dummyjson:
  product-url: https://dummyjson.com/products